version: "3"
services:
  fatura_db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data1
    environment:
      POSTGRES_PASSWORD: fatura
      POSTGRES_USER: fatura
      POSTGRES_DB: fatura
    ports:
      - "5436:5432"

volumes:
  db-data:
    driver: local